import{S as d,a as f,i as y}from"./assets/vendor-a57f9cde.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&m(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerpolicy&&(a.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?a.credentials="include":t.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function m(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();const h="/goit-js-hw-12/assets/alert-7962080a.svg",b="https://pixabay.com/api/",r={key:"40878457-91c7c8077e8a58c5727309d44",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:1},v=document.querySelector(".form"),u=document.querySelector(".searchTerm"),w=document.querySelector(".search-btn"),c=document.querySelector(".get-more-btn"),L=document.querySelector(".loader"),g=document.querySelector(".gallery"),S=new d(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250});v.addEventListener("submit",e=>{if(e.preventDefault(),u.value.trim().length<3){l("Please, enter search term!");return}g.innerHTML="",o(!0),r.q=u.value.trim(),r.page=1,p()});c.addEventListener("click",()=>{r.page+=1,o(!0),p()});async function p(){try{const e=await f.get(b,{params:r});console.log(e),k(e.data)}catch(e){l(e.toString()),o(!1)}}function k(e){if(e.total===0){l("Sorry, there are no images matching your search query. Please try again!"),o(!1);return}const n=e.hits.map(s=>`<a class="gallery-link" href="${s.largeImageURL}"><span class="gallery-item"><img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" title="${s.tags}" /></span>
            <span class="img-stat">
            <span class="img-stat-item"><span class="img-stat-title">Likes</span><span class="img-stat-val">${s.likes}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Views</span><span class="img-stat-val">${s.views}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Comments</span><span class="img-stat-val">${s.comments}</span></span>
            <span class="img-stat-item"><span class="img-stat-title">Downloads</span><span class="img-stat-val">${s.downloads}</span></span>
            </span>
            </a>`).join("");if(o(!1),g.insertAdjacentHTML("beforeend",n),r.page===1&&(c.style.display="block"),Math.ceil(e.totalHits/r.per_page)===r.page&&(c.style.display="none",l("We're sorry, but you've reached the end of search results.")),S.refresh(),r.page>1){const s=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:s.height*2,left:0,behavior:"smooth"})}}function o(e=!0){L.style.display=e?"inline-block":"none",w.disabled=e}function l(e){y.show({position:"center",iconUrl:h,messageColor:"#FAFAFB",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0,message:e})}
//# sourceMappingURL=commonHelpers.js.map
